// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: proto/iplist.proto

package iplist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewIplist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Done        bool   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *NewIplist) Reset() {
	*x = NewIplist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iplist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewIplist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewIplist) ProtoMessage() {}

func (x *NewIplist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iplist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewIplist.ProtoReflect.Descriptor instead.
func (*NewIplist) Descriptor() ([]byte, []int) {
	return file_proto_iplist_proto_rawDescGZIP(), []int{0}
}

func (x *NewIplist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewIplist) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NewIplist) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type Iplist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Done        bool   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	Id          string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Iplist) Reset() {
	*x = Iplist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iplist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Iplist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Iplist) ProtoMessage() {}

func (x *Iplist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iplist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Iplist.ProtoReflect.Descriptor instead.
func (*Iplist) Descriptor() ([]byte, []int) {
	return file_proto_iplist_proto_rawDescGZIP(), []int{1}
}

func (x *Iplist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Iplist) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Iplist) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Iplist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_iplist_proto protoreflect.FileDescriptor

var file_proto_iplist_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x70, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x09, 0x4e,
	0x65, 0x77, 0x49, 0x70, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f,
	0x6e, 0x65, 0x22, 0x62, 0x0a, 0x06, 0x49, 0x70, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x42, 0x0a, 0x0d, 0x49, 0x70, 0x6c, 0x69, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x49, 0x70, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x65, 0x77, 0x49, 0x70, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x49, 0x70, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x69, 0x6c,
	0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x70, 0x6c, 0x69, 0x73, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_iplist_proto_rawDescOnce sync.Once
	file_proto_iplist_proto_rawDescData = file_proto_iplist_proto_rawDesc
)

func file_proto_iplist_proto_rawDescGZIP() []byte {
	file_proto_iplist_proto_rawDescOnce.Do(func() {
		file_proto_iplist_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_iplist_proto_rawDescData)
	})
	return file_proto_iplist_proto_rawDescData
}

var file_proto_iplist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_iplist_proto_goTypes = []interface{}{
	(*NewIplist)(nil), // 0: proto.NewIplist
	(*Iplist)(nil),    // 1: proto.Iplist
}
var file_proto_iplist_proto_depIdxs = []int32{
	0, // 0: proto.IplistService.CreateIplist:input_type -> proto.NewIplist
	1, // 1: proto.IplistService.CreateIplist:output_type -> proto.Iplist
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_iplist_proto_init() }
func file_proto_iplist_proto_init() {
	if File_proto_iplist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_iplist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewIplist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iplist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Iplist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_iplist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iplist_proto_goTypes,
		DependencyIndexes: file_proto_iplist_proto_depIdxs,
		MessageInfos:      file_proto_iplist_proto_msgTypes,
	}.Build()
	File_proto_iplist_proto = out.File
	file_proto_iplist_proto_rawDesc = nil
	file_proto_iplist_proto_goTypes = nil
	file_proto_iplist_proto_depIdxs = nil
}
