// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: proto/iplist.proto

package iplist

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IplistService_ResolveUser_FullMethodName      = "/proto.IplistService/ResolveUser"
	IplistService_ResolveIpAddress_FullMethodName = "/proto.IplistService/ResolveIpAddress"
)

// IplistServiceClient is the client API for IplistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IplistServiceClient interface {
	ResolveUser(ctx context.Context, in *SourceIp, opts ...grpc.CallOption) (*UserGroups, error)
	ResolveIpAddress(ctx context.Context, opts ...grpc.CallOption) (IplistService_ResolveIpAddressClient, error)
}

type iplistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIplistServiceClient(cc grpc.ClientConnInterface) IplistServiceClient {
	return &iplistServiceClient{cc}
}

func (c *iplistServiceClient) ResolveUser(ctx context.Context, in *SourceIp, opts ...grpc.CallOption) (*UserGroups, error) {
	out := new(UserGroups)
	err := c.cc.Invoke(ctx, IplistService_ResolveUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iplistServiceClient) ResolveIpAddress(ctx context.Context, opts ...grpc.CallOption) (IplistService_ResolveIpAddressClient, error) {
	stream, err := c.cc.NewStream(ctx, &IplistService_ServiceDesc.Streams[0], IplistService_ResolveIpAddress_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &iplistServiceResolveIpAddressClient{stream}
	return x, nil
}

type IplistService_ResolveIpAddressClient interface {
	Send(*SourceIp) error
	Recv() (*UserGroups, error)
	grpc.ClientStream
}

type iplistServiceResolveIpAddressClient struct {
	grpc.ClientStream
}

func (x *iplistServiceResolveIpAddressClient) Send(m *SourceIp) error {
	return x.ClientStream.SendMsg(m)
}

func (x *iplistServiceResolveIpAddressClient) Recv() (*UserGroups, error) {
	m := new(UserGroups)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IplistServiceServer is the server API for IplistService service.
// All implementations must embed UnimplementedIplistServiceServer
// for forward compatibility
type IplistServiceServer interface {
	ResolveUser(context.Context, *SourceIp) (*UserGroups, error)
	ResolveIpAddress(IplistService_ResolveIpAddressServer) error
	mustEmbedUnimplementedIplistServiceServer()
}

// UnimplementedIplistServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIplistServiceServer struct {
}

func (UnimplementedIplistServiceServer) ResolveUser(context.Context, *SourceIp) (*UserGroups, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveUser not implemented")
}
func (UnimplementedIplistServiceServer) ResolveIpAddress(IplistService_ResolveIpAddressServer) error {
	return status.Errorf(codes.Unimplemented, "method ResolveIpAddress not implemented")
}
func (UnimplementedIplistServiceServer) mustEmbedUnimplementedIplistServiceServer() {}

// UnsafeIplistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IplistServiceServer will
// result in compilation errors.
type UnsafeIplistServiceServer interface {
	mustEmbedUnimplementedIplistServiceServer()
}

func RegisterIplistServiceServer(s grpc.ServiceRegistrar, srv IplistServiceServer) {
	s.RegisterService(&IplistService_ServiceDesc, srv)
}

func _IplistService_ResolveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceIp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IplistServiceServer).ResolveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IplistService_ResolveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IplistServiceServer).ResolveUser(ctx, req.(*SourceIp))
	}
	return interceptor(ctx, in, info, handler)
}

func _IplistService_ResolveIpAddress_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IplistServiceServer).ResolveIpAddress(&iplistServiceResolveIpAddressServer{stream})
}

type IplistService_ResolveIpAddressServer interface {
	Send(*UserGroups) error
	Recv() (*SourceIp, error)
	grpc.ServerStream
}

type iplistServiceResolveIpAddressServer struct {
	grpc.ServerStream
}

func (x *iplistServiceResolveIpAddressServer) Send(m *UserGroups) error {
	return x.ServerStream.SendMsg(m)
}

func (x *iplistServiceResolveIpAddressServer) Recv() (*SourceIp, error) {
	m := new(SourceIp)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IplistService_ServiceDesc is the grpc.ServiceDesc for IplistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IplistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IplistService",
	HandlerType: (*IplistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveUser",
			Handler:    _IplistService_ResolveUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ResolveIpAddress",
			Handler:       _IplistService_ResolveIpAddress_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/iplist.proto",
}
